// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIKWlx5aTjq1BBlkMzS5bqsARYIH-t05I',
    appId: '1:307325496466:web:46cc9da2f7093f25298a4b',
    messagingSenderId: '307325496466',
    projectId: 'validotp',
    authDomain: 'validotp.firebaseapp.com',
    storageBucket: 'validotp.appspot.com',
    measurementId: 'G-EC799W24LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdpBLToBfji6A4976jG24TT3s0IsQpfI',
    appId: '1:307325496466:android:f6df2d780890fe09298a4b',
    messagingSenderId: '307325496466',
    projectId: 'validotp',
    storageBucket: 'validotp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTVCv6aTkWkGJNDV61TSa5m0Et4beiyWo',
    appId: '1:307325496466:ios:664643b954e0c245298a4b',
    messagingSenderId: '307325496466',
    projectId: 'validotp',
    storageBucket: 'validotp.appspot.com',
    iosBundleId: 'com.example.valid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTVCv6aTkWkGJNDV61TSa5m0Et4beiyWo',
    appId: '1:307325496466:ios:664643b954e0c245298a4b',
    messagingSenderId: '307325496466',
    projectId: 'validotp',
    storageBucket: 'validotp.appspot.com',
    iosBundleId: 'com.example.valid',
  );

}